require 'dependabot/kiln/file_fetcher'
require 'dependabot/kiln/file_parser'
require 'dependabot/kiln/file_updater'
require 'dependabot/kiln/helpers'
require 'dependabot/kiln/metadata_finder'
require 'dependabot/kiln/requirement'
require 'dependabot/kiln/update_checker'
require 'dependabot/kiln/version'
